# This stage names are used for stashing and un-stashing of files

initS4sdkPipeline:
  unstash: []
  stashes:
    - name: "SOURCE"
      includes: "**"
      excludes: "**/.git/**, s4hana_pipeline/reports/**"
    #    Following stash will contain only empty directory.
    #    This is required to support the concurrency in the stashing mechanism where
    #    we merge the stashes from multiple stages into one.
    - name: "REPORTS"
      includes: "s4hana_pipeline/reports/**"

build:
  unstash: ["SOURCE"]
  stashes:
    - name: "DIST"
      includes: "**/dist/**"
    - name: "NODE_MODULES"
      includes: "**/node_modules/**"
    - name: "PACKAGE_LOCK"
      includes: "**/package-lock.json, **/npm-shrinkwrap.json"

unitTests:
  unstash: ["SOURCE", "DIST", "NODE_MODULES"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**"

frontendUnitTests:
  unstash: ["SOURCE", "DIST", "NODE_MODULES"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**"

backendIntegrationTests:
  unstash: ["SOURCE", "DIST", "NODE_MODULES"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**"

frontendIntegrationTests:
  unstash: ["SOURCE", "DIST", "NODE_MODULES"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**"

package:
  unstash: ["SOURCE", "DIST", "NODE_MODULES"]
  stashes:
    - name: "DEPLOYMENTARTIFACT"
      includes: "deployment/**"

sonarQubeScan:
  unstash: ['SOURCE', 'NODE_MODULES', 'DIST']
  stashes: []

npmAudit:
  unstash: ["SOURCE", "PACKAGE_LOCK"]
  stashes: []

s4SdkQualityChecks:
  unstash: ["SOURCE", "DIST", "REPORTS"]

lint:
  unstash: ["SOURCE"]

whitesourceScan:
  unstash: ["SOURCE", "NODE_MODULES", "PACKAGE_LOCK"]
  stashes: []

checkmarxScan:
  unstash: ["SOURCE"]
  stashes: []

endToEndTests:
  unstash: ["SOURCE", "DEPLOYMENTARTIFACT", "NODE_MODULES"]
  stashes: []

artifactDeployment:
  unstash: ["SOURCE", "DEPLOYMENTARTIFACT"]
  stashes: []

productionDeployment:
  unstash: ["DEPLOYMENTARTIFACT", "SOURCE", "NODE_MODULES"]
  stashes: []
