# This stage names are used for stashing and un-stashing of files


initS4sdkPipeline:
  unstash: []
  stashes:
  - name: "SOURCE"
    includes: "**/*.*"
    excludes: "'pipelines/**, **/.git/**"
  - name: "PIPELINE"
    includes: "'pipelines/**"
    excludes: "'pipelines/.git/**"
  - name: "REPORTS"
    includes: "s4hana_pipeline/reports/**"
  - name: "M2"
    includes: "s4hana_pipeline/maven_local_repo/**"
  - name: "TARGET"
    includes: "**/target/**"
  - name: "NODE_MODULES"
    includes: "node_modules/**"

build:
  unstash: ['SOURCE','M2']
  stashes:
  - name: "M2"
    includes: "s4hana_pipeline/maven_local_repo/**"
  - name: "TARGET"
    includes: "*.mtar, **/target/**, target/**"
  - name: "NODE_MODULES"
    includes: "**/node_modules/**, node_modules/**"
  - name: "PACKAGE_LOCK"
    includes: "**/package-lock.json, **/npm-shrinkwrap.json"

unitTests:
  unstash: ['SOURCE', 'M2', 'TARGET']
  stashes:
  - name: "REPORTS"
    merge: true
    includes: "s4hana_pipeline/reports/**"

integrationTests:
  unstash: ['SOURCE', 'M2', 'TARGET']
  stashes:
  - name: "REPORTS"
    merge: true
    includes: "s4hana_pipeline/reports/**"

staticCodeChecks:
  unstash: ['SOURCE', 'TARGET', 'REPORTS', 'M2']
  stashes:
  - name: "REPORTS"
    merge: true
    includes: "s4hana_pipeline/reports/**"

lint:
  unstash: ['SOURCE', 'NODE_MODULES', 'PACKAGE_LOCK']

checkmarxScan:
  unstash: ['SOURCE', 'TARGET', 'REPORTS', 'M2']
  stashes: []

whitesourceScan:
  unstash: ['SOURCE', 'M2', 'NODE_MODULES']
  stashes: []

sourceClearScan:
  unstash: ['SOURCE', 'M2', 'NODE_MODULES']
  stashes: []

additionalTools:
  unstash: ['SOURCE', 'M2', 'NODE_MODULES']
  stashes: []

fortifyScan:
  unstash: ['SOURCE', 'M2']
  stashes: []

npmAudit:
  unstash: ['SOURCE', "PACKAGE_LOCK"]
  stashes: []

frontendUnitTests:
  unstash: ['SOURCE', 'NODE_MODULES']
  stashes: []

endToEndTests:
  unstash: ['SOURCE', 'TARGET', 'NODE_MODULES']
  stashes: []

performanceTests:
  unstash: ['SOURCE', 'TARGET']
  stashes:
  - name: "REPORTS"
    merge: true
    includes: "s4hana_pipeline/reports/**"

s4SdkQualityChecks:
  unstash: ['SOURCE', 'M2', 'TARGET',  'REPORTS']
  stashes:
  - name: "REPORTS"
    includes: "s4hana_pipeline/reports/**"

artifactDeployment:
  unstash: ['SOURCE', 'TARGET', 'NODE_MODULES']
  stashes: []

productionDeployment:
  unstash: ['SOURCE', 'TARGET', 'NODE_MODULES']
  stashes: []

