name: Example workflow

on: [push]

jobs:
  example:
    name: Example Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v1.0.0
        with:
          minikube version: 'v1.5.2'
          kubernetes version: 'v1.16.2'
      - uses: azure/setup-helm@v1
        id: install
      - name: Interact with the cluster
        run: |
          kubectl get nodes
          kubectl get pods
          kubectl cluster-info
          kubectl get pods -n kube-system
          helm init
          helm repo add stable https://kubernetes-charts.storage.googleapis.com/
          helm repo update
          helm install --generate-name stable/jenkins -f values.yaml
          kubectl --namespace kube-system get pods
